### ISSUE TITLE
comparing individual days

### ISSUE THREAD

**Issue by tkrumrei** [LHesse-UM/StudyProject2024#13]

**Comment by tlehman1** [comment]
4 Tage an denen 4 Mannschaften Fußball gespielt haben:

**Comment by tlehman1** [comment]
![Bildschirmfoto 2024-12-02 um 21 09 53](https://github.com/user-attachments/assets/b7c118b8-1bb8-4010-8149-7357a25d423b)

**Comment by tlehman1** [comment]
<img width="1216" alt="Dates" src="https://github.com/user-attachments/assets/101eb5ec-e4fc-43d9-b487-03c72953c1bf">
